# Generated by Django 4.0.1 on 2022-01-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accentcolor',
            name='color_palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accent_colors', to='api.colorpalette'),
        ),
        migrations.AlterField(
            model_name='dominantcolor',
            name='color_palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominant_colors', to='api.colorpalette'),
        ),
        migrations.RemoveField(
            model_name='favouritepalette',
            name='favorite_palettes',
        ),
        migrations.AddField(
            model_name='favouritepalette',
            name='favorite_palettes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_palattes', to='api.colorpalette'),
            preserve_default=False,
        ),
    ]
